//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakilaConsoleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SakilaConsoleApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO actor (first_name, last_name) 
        ///	VALUES (@firstname, @lastname);
        ///
        ///SELECT SCOPE_IDENTITY();.
        /// </summary>
        internal static string AddActor {
            get {
                return ResourceManager.GetString("AddActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT customer_id, first_name, last_name FROM customer.
        /// </summary>
        internal static string GetAllCustomers {
            get {
                return ResourceManager.GetString("GetAllCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- DECLARE @film_id INT = 1
        ///
        ///SELECT 
        ///	film_id, 
        ///	title, 
        ///	[description]
        ///FROM 
        ///	film 
        ///WHERE 
        ///	film_id = @film_id
        ///.
        /// </summary>
        internal static string GetFilmById {
            get {
                return ResourceManager.GetString("GetFilmById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	rating,
        ///	COUNT(*) AS rating_count
        ///FROM 
        ///	film 
        ///GROUP BY
        ///	rating.
        /// </summary>
        internal static string GetFilmsByRating {
            get {
                return ResourceManager.GetString("GetFilmsByRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- DECLARE @title VARCHAR(255) = &apos;AC%&apos;
        ///
        ///SELECT film_id, title, [description] FROM film WHERE title LIKE @title .
        /// </summary>
        internal static string GetFilmsByTitle {
            get {
                return ResourceManager.GetString("GetFilmsByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP(3)
        ///    DATENAME(WEEKDAY, rental_date) AS rental_day,
        ///    COUNT(*) AS rental_count
        ///FROM 
        ///    rental
        ///GROUP BY
        ///    DATENAME(WEEKDAY, rental_date)
        ///ORDER BY
        ///    rental_count DESC.
        /// </summary>
        internal static string GetTotalRentalsByWeekday {
            get {
                return ResourceManager.GetString("GetTotalRentalsByWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE actor 
        ///WHERE
        ///	actor_id = @id.
        /// </summary>
        internal static string RemoveActor {
            get {
                return ResourceManager.GetString("RemoveActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE actor 
        /// SET 
        ///	first_name = @firstname,
        ///	last_name  = @lastname
        ///WHERE
        ///	actor_id = @id.
        /// </summary>
        internal static string UpdateActor {
            get {
                return ResourceManager.GetString("UpdateActor", resourceCulture);
            }
        }
    }
}
